// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/vinigracindo/mercado-fresco-stranger-strings/internal/product_records/domain"
)

// ProductRecordsRepository is an autogenerated mock type for the ProductRecordsRepository type
type ProductRecordsRepository struct {
	mock.Mock
}

// CountByProductId provides a mock function with given fields: ctx, productId
func (_m *ProductRecordsRepository) CountByProductId(ctx context.Context, productId int64) (int64, error) {
	ret := _m.Called(ctx, productId)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, int64) int64); ok {
		r0 = rf(ctx, productId)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, productId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, productRecords
func (_m *ProductRecordsRepository) Create(ctx context.Context, productRecords *domain.ProductRecords) (*domain.ProductRecords, error) {
	ret := _m.Called(ctx, productRecords)

	var r0 *domain.ProductRecords
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ProductRecords) *domain.ProductRecords); ok {
		r0 = rf(ctx, productRecords)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProductRecords)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *domain.ProductRecords) error); ok {
		r1 = rf(ctx, productRecords)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewProductRecordsRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewProductRecordsRepository creates a new instance of ProductRecordsRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProductRecordsRepository(t mockConstructorTestingTNewProductRecordsRepository) *ProductRecordsRepository {
	mock := &ProductRecordsRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
