// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	warehouse "github.com/vinigracindo/mercado-fresco-stranger-strings/internal/domains/warehouse"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: adress, tel, code, mintemp, mincap
func (_m *Service) Create(adress string, tel string, code string, mintemp float64, mincap int64) (warehouse.WarehouseModel, error) {
	ret := _m.Called(adress, tel, code, mintemp, mincap)

	var r0 warehouse.WarehouseModel
	if rf, ok := ret.Get(0).(func(string, string, string, float64, int64) warehouse.WarehouseModel); ok {
		r0 = rf(adress, tel, code, mintemp, mincap)
	} else {
		r0 = ret.Get(0).(warehouse.WarehouseModel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string, string, float64, int64) error); ok {
		r1 = rf(adress, tel, code, mintemp, mincap)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *Service) Delete(id int64) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *Service) GetAll() ([]warehouse.WarehouseModel, error) {
	ret := _m.Called()

	var r0 []warehouse.WarehouseModel
	if rf, ok := ret.Get(0).(func() []warehouse.WarehouseModel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]warehouse.WarehouseModel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *Service) GetById(id int64) (warehouse.WarehouseModel, error) {
	ret := _m.Called(id)

	var r0 warehouse.WarehouseModel
	if rf, ok := ret.Get(0).(func(int64) warehouse.WarehouseModel); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(warehouse.WarehouseModel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTempAndCap provides a mock function with given fields: id, mintemp, mincap
func (_m *Service) UpdateTempAndCap(id int64, mintemp float64, mincap int64) (warehouse.WarehouseModel, error) {
	ret := _m.Called(id, mintemp, mincap)

	var r0 warehouse.WarehouseModel
	if rf, ok := ret.Get(0).(func(int64, float64, int64) warehouse.WarehouseModel); ok {
		r0 = rf(id, mintemp, mincap)
	} else {
		r0 = ret.Get(0).(warehouse.WarehouseModel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64, float64, int64) error); ok {
		r1 = rf(id, mintemp, mincap)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
