// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	warehouse "github.com/vinigracindo/mercado-fresco-stranger-strings/internal/warehouse/domain"
)

// WarehouseService is an autogenerated mock type for the WarehouseService type
type WarehouseService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, adress, tel, code, mintemp, mincap, locality
func (_m *WarehouseService) Create(ctx context.Context, adress string, tel string, code string, mintemp float64, mincap int64, locality int64) (warehouse.WarehouseModel, error) {
	ret := _m.Called(ctx, adress, tel, code, mintemp, mincap, locality)

	var r0 warehouse.WarehouseModel
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, float64, int64, int64) warehouse.WarehouseModel); ok {
		r0 = rf(ctx, adress, tel, code, mintemp, mincap, locality)
	} else {
		r0 = ret.Get(0).(warehouse.WarehouseModel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, float64, int64, int64) error); ok {
		r1 = rf(ctx, adress, tel, code, mintemp, mincap, locality)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *WarehouseService) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *WarehouseService) GetAll(ctx context.Context) ([]warehouse.WarehouseModel, error) {
	ret := _m.Called(ctx)

	var r0 []warehouse.WarehouseModel
	if rf, ok := ret.Get(0).(func(context.Context) []warehouse.WarehouseModel); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]warehouse.WarehouseModel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *WarehouseService) GetById(ctx context.Context, id int64) (warehouse.WarehouseModel, error) {
	ret := _m.Called(ctx, id)

	var r0 warehouse.WarehouseModel
	if rf, ok := ret.Get(0).(func(context.Context, int64) warehouse.WarehouseModel); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(warehouse.WarehouseModel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTempAndCap provides a mock function with given fields: ctx, id, mintemp, mincap
func (_m *WarehouseService) UpdateTempAndCap(ctx context.Context, id int64, mintemp float64, mincap int64) (warehouse.WarehouseModel, error) {
	ret := _m.Called(ctx, id, mintemp, mincap)

	var r0 warehouse.WarehouseModel
	if rf, ok := ret.Get(0).(func(context.Context, int64, float64, int64) warehouse.WarehouseModel); ok {
		r0 = rf(ctx, id, mintemp, mincap)
	} else {
		r0 = ret.Get(0).(warehouse.WarehouseModel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64, float64, int64) error); ok {
		r1 = rf(ctx, id, mintemp, mincap)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewWarehouseService interface {
	mock.TestingT
	Cleanup(func())
}

// NewWarehouseService creates a new instance of WarehouseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWarehouseService(t mockConstructorTestingTNewWarehouseService) *WarehouseService {
	mock := &WarehouseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
