// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	warehouse "github.com/vinigracindo/mercado-fresco-stranger-strings/internal/warehouse/domain"
)

// WarehouseRepository is an autogenerated mock type for the WarehouseRepository type
type WarehouseRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: wr
func (_m *WarehouseRepository) Create(wr *warehouse.WarehouseModel) (warehouse.WarehouseModel, error) {
	ret := _m.Called(wr)

	var r0 warehouse.WarehouseModel
	if rf, ok := ret.Get(0).(func(*warehouse.WarehouseModel) warehouse.WarehouseModel); ok {
		r0 = rf(wr)
	} else {
		r0 = ret.Get(0).(warehouse.WarehouseModel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*warehouse.WarehouseModel) error); ok {
		r1 = rf(wr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateID provides a mock function with given fields:
func (_m *WarehouseRepository) CreateID() int64 {
	ret := _m.Called()

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// Delete provides a mock function with given fields: id
func (_m *WarehouseRepository) Delete(id int64) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *WarehouseRepository) GetAll() ([]warehouse.WarehouseModel, error) {
	ret := _m.Called()

	var r0 []warehouse.WarehouseModel
	if rf, ok := ret.Get(0).(func() []warehouse.WarehouseModel); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]warehouse.WarehouseModel)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *WarehouseRepository) GetById(id int64) (warehouse.WarehouseModel, error) {
	ret := _m.Called(id)

	var r0 warehouse.WarehouseModel
	if rf, ok := ret.Get(0).(func(int64) warehouse.WarehouseModel); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(warehouse.WarehouseModel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, wh
func (_m *WarehouseRepository) Update(id int64, wh *warehouse.WarehouseModel) (warehouse.WarehouseModel, error) {
	ret := _m.Called(id, wh)

	var r0 warehouse.WarehouseModel
	if rf, ok := ret.Get(0).(func(int64, *warehouse.WarehouseModel) warehouse.WarehouseModel); ok {
		r0 = rf(id, wh)
	} else {
		r0 = ret.Get(0).(warehouse.WarehouseModel)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64, *warehouse.WarehouseModel) error); ok {
		r1 = rf(id, wh)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewWarehouseRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewWarehouseRepository creates a new instance of WarehouseRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWarehouseRepository(t mockConstructorTestingTNewWarehouseRepository) *WarehouseRepository {
	mock := &WarehouseRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
