// Code generated by mockery v2.13.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/vinigracindo/mercado-fresco-stranger-strings/internal/seller/domain"
)

// ServiceSeller is an autogenerated mock type for the ServiceSeller type
type ServiceSeller struct {
	mock.Mock
}

// Create provides a mock function with given fields: cid, companyName, address, telephone
func (_m *ServiceSeller) Create(cid int64, companyName string, address string, telephone string) (domain.Seller, error) {
	ret := _m.Called(cid, companyName, address, telephone)

	var r0 domain.Seller
	if rf, ok := ret.Get(0).(func(int64, string, string, string) domain.Seller); ok {
		r0 = rf(cid, companyName, address, telephone)
	} else {
		r0 = ret.Get(0).(domain.Seller)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64, string, string, string) error); ok {
		r1 = rf(cid, companyName, address, telephone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *ServiceSeller) Delete(id int64) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields:
func (_m *ServiceSeller) GetAll() ([]domain.Seller, error) {
	ret := _m.Called()

	var r0 []domain.Seller
	if rf, ok := ret.Get(0).(func() []domain.Seller); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Seller)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *ServiceSeller) GetById(id int64) (domain.Seller, error) {
	ret := _m.Called(id)

	var r0 domain.Seller
	if rf, ok := ret.Get(0).(func(int64) domain.Seller); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Seller)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, address, telephone
func (_m *ServiceSeller) Update(id int64, address string, telephone string) (domain.Seller, error) {
	ret := _m.Called(id, address, telephone)

	var r0 domain.Seller
	if rf, ok := ret.Get(0).(func(int64, string, string) domain.Seller); ok {
		r0 = rf(id, address, telephone)
	} else {
		r0 = ret.Get(0).(domain.Seller)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64, string, string) error); ok {
		r1 = rf(id, address, telephone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewServiceSeller interface {
	mock.TestingT
	Cleanup(func())
}

// NewServiceSeller creates a new instance of ServiceSeller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServiceSeller(t mockConstructorTestingTNewServiceSeller) *ServiceSeller {
	mock := &ServiceSeller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
